In [1]:
import numpy as np
import tensorflow as tf

In [2]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [3]:
from keras.datasets import cifar10
import numpy as np
np.random.seed(10)
# 导入数据集，如果没有就会自动下载
(x_img_train,y_label_train),(x_img_test, y_label_test)=cifar10.load_data()
print('train:',len(x_img_train))
print('test :',len(x_img_test))
print('train_image :',x_img_train.shape)
print('train_label :',y_label_train.shape)
print('test_image :',x_img_test.shape)
print('test_label :',y_label_test.shape)


Using TensorFlow backend.


train: 50000
test : 10000
train_image : (50000, 32, 32, 3)
train_label : (50000, 1)
test_image : (10000, 32, 32, 3)
test_label : (10000, 1)


In [11]:
print(x_img_train[0][0][0]) #（50000，32，32，3）
x_img_train_normalize = x_img_train.astype('float32') / 255.0
x_img_test_normalize = x_img_test.astype('float32') / 255.0
print(x_img_train_normalize[0][0][0])

[59 62 63]
[0.23137255 0.24313726 0.24705882]


In [4]:
from keras import Sequential
model=Sequential()

In [5]:
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import Adam
import keras

In [6]:
batch_size=30
input_shape=(32,32,3)
num_classes=10


In [7]:
# model.add(Conv2D(32, kernel_size=(5, 5), strides=(1, 1),
#                  activation='relu',
#                  input_shape=input_shape))
model.add(Conv2D(filters=32,kernel_size=(3,3),
                 input_shape=(32, 32,3), 
                 activation='relu', 
                 padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(64, (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.05),
              metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
from keras.utils import np_utils
y_label_train_OneHot = np_utils.to_categorical(y_label_train)
y_label_test_OneHot = np_utils.to_categorical(y_label_test)
print(y_label_train_OneHot.shape)
print(y_label_train_OneHot[:5])


(50000, 10)
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:

epochs=5
model.fit(x_img_train, y_label_train_OneHot,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_img_test, y_label_test_OneHot)
          )

Instructions for updating:
Use tf.cast instead.
Train on 50000 samples, validate on 10000 samples
Epoch 1/5
50000/50000 [==============================] - 13s 250us/step - loss: 14.5052 - acc: 0.1000 - val_loss: 14.5063 - val_acc: 0.1000
Epoch 2/5
50000/50000 [==============================] - 8s 150us/step - loss: 14.5063 - acc: 0.1000 - val_loss: 14.5063 - val_acc: 0.1000
Epoch 3/5
50000/50000 [==============================] - 7s 150us/step - loss: 14.5063 - acc: 0.1000 - val_loss: 14.5063 - val_acc: 0.1000
Epoch 4/5
50000/50000 [==============================] - 8s 151us/step - loss: 14.5063 - acc: 0.1000 - val_loss: 14.5063 - val_acc: 0.1000
Epoch 5/5
50000/50000 [==============================] - 7s 150us/step - loss: 14.5063 - acc: 0.1000 - val_loss: 14.5063 - val_acc: 0.1000


In [12]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.05),
              metrics=['accuracy'])
model.fit(x_img_train_normalize, y_label_train_OneHot,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_img_test_normalize, y_label_test_OneHot)
          )

Train on 50000 samples, validate on 10000 samples
Epoch 1/5
50000/50000 [==============================] - 8s 158us/step - loss: 1.6822 - acc: 0.3920 - val_loss: 1.4130 - val_acc: 0.4888
Epoch 2/5
50000/50000 [==============================] - 8s 152us/step - loss: 1.1826 - acc: 0.5821 - val_loss: 1.1323 - val_acc: 0.6032
Epoch 3/5
50000/50000 [==============================] - 8s 153us/step - loss: 0.9641 - acc: 0.6626 - val_loss: 1.0541 - val_acc: 0.6332
Epoch 4/5
50000/50000 [==============================] - 8s 150us/step - loss: 0.7891 - acc: 0.7257 - val_loss: 0.9200 - val_acc: 0.6852
Epoch 5/5
50000/50000 [==============================] - 7s 149us/step - loss: 0.6340 - acc: 0.7797 - val_loss: 0.8912 - val_acc: 0.6982


In [13]:
epochs=30
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.05),
              metrics=['accuracy'])
model.fit(x_img_train_normalize, y_label_train_OneHot,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_img_test_normalize, y_label_test_OneHot)
          )

Train on 50000 samples, validate on 10000 samples
Epoch 1/30
50000/50000 [==============================] - 8s 156us/step - loss: 0.4789 - acc: 0.8347 - val_loss: 0.9585 - val_acc: 0.6952
Epoch 2/30
50000/50000 [==============================] - 7s 150us/step - loss: 0.3299 - acc: 0.8864 - val_loss: 1.0142 - val_acc: 0.7037
Epoch 3/30
50000/50000 [==============================] - 8s 151us/step - loss: 0.2175 - acc: 0.9266 - val_loss: 1.1006 - val_acc: 0.7060
Epoch 4/30
50000/50000 [==============================] - 7s 149us/step - loss: 0.1408 - acc: 0.9532 - val_loss: 1.3522 - val_acc: 0.6889
Epoch 5/30
50000/50000 [==============================] - 8s 150us/step - loss: 0.0842 - acc: 0.9739 - val_loss: 1.3392 - val_acc: 0.7067
Epoch 6/30
50000/50000 [==============================] - 8s 150us/step - loss: 0.0581 - acc: 0.9819 - val_loss: 1.4090 - val_acc: 0.7102
Epoch 7/30
50000/50000 [==============================] - 8s 151us/step - loss: 0.0484 - acc: 0.9854 - val_loss: 1.4822 - 

## try drop out to fight overfittng

In [14]:
model=Sequential()
model.add(Conv2D(filters=32,kernel_size=(3,3),
                 input_shape=(32, 32,3), 
                 activation='relu', 
                 padding='same'))
model.add(Dropout(rate=0.25))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(64, (5, 5), activation='relu'))
model.add(Dropout(rate=0.25))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dropout(rate=0.25))
model.add(Dense(1000, activation='relu'))
model.add(Dropout(rate=0.25))
model.add(Dense(num_classes, activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.05),
              metrics=['accuracy'])

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


## regularation has obvious effect

In [16]:
epochs=30
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.02),
              metrics=['accuracy'])
model.fit(x_img_train_normalize, y_label_train_OneHot,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_img_test_normalize, y_label_test_OneHot)
          )

Train on 50000 samples, validate on 10000 samples
Epoch 1/30
50000/50000 [==============================] - 10s 196us/step - loss: 0.9947 - acc: 0.6516 - val_loss: 1.0587 - val_acc: 0.6528
Epoch 2/30
50000/50000 [==============================] - 9s 187us/step - loss: 0.9448 - acc: 0.6651 - val_loss: 1.0047 - val_acc: 0.6847
Epoch 3/30
50000/50000 [==============================] - 9s 186us/step - loss: 0.8928 - acc: 0.6878 - val_loss: 0.9497 - val_acc: 0.6923
Epoch 4/30
50000/50000 [==============================] - 9s 186us/step - loss: 0.8457 - acc: 0.7030 - val_loss: 0.9674 - val_acc: 0.6840
Epoch 5/30
50000/50000 [==============================] - 9s 187us/step - loss: 0.8043 - acc: 0.7173 - val_loss: 0.9339 - val_acc: 0.7009
Epoch 6/30
50000/50000 [==============================] - 9s 185us/step - loss: 0.7547 - acc: 0.7351 - val_loss: 0.9062 - val_acc: 0.7030
Epoch 7/30
50000/50000 [==============================] - 10s 191us/step - loss: 0.7119 - acc: 0.7495 - val_loss: 0.8478 